[package]
name = "rembrandt_kernels"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "rembrandt_kernels"
path = "lib.rs"

[dependencies.cuda]
path = "../libcuda"
